(uiop:define-package :alu-test
  (:mix #:cl #:alu.prelude #:fiveam #:serapeum)
  (:shadow #:time)
  (:local-nicknames (:util     :alu.utils)
                    (:spc      :alu.pass.spec)
                    (:storage  :alu.storage)
                    (:anf      :alu.pass.anf)
                    (:closure  :alu.closure)
                    (:expand   :alu.pass.expanded)
                    (:relocate :alu.pass.relocation)
                    (:vamp     :alu.vampir)
                    (:pass     :alu.pass)
                    (:vspc     :alu.vampir.spec)
                    (:prld     :alu.prelude))
  (:export #:run-tests))

(in-package :alu-test)
