(uiop:define-package :alu-test
  (:mix #:cl #:alu.prelude #:fiveam #:serapeum)
  (:shadow #:time)
  (:local-nicknames (:util     :alu.utils)
                    (:ir       :alu.ir)
                    (:storage  :alu.storage)
                    (:emit     :alu.spec.emit)
                    (:anf      :alu.pass.anf)
                    (:closure  :alu.closure)
                    (:expand   :alu.pass.expanded)
                    (:relocate :alu.pass.relocation)
                    (:vamp     :alu.vampir)
                    (:dep      :alu.pass.dependencies)
                    (:eval     :alu.pass.evaluate-body)
                    (:check    :alu.typechecker)
                    (:pass     :alu.pass)
                    (:pipeline :alu.pipeline)
                    (:vspc     :alu.vampir.spec)
                    (:prld     :alu.prelude))
  (:export #:run-tests))

(in-package :alu-test)
